parallelism = 2

[graph]
edge_list_input_file = "edges-compass.csv.gz"
vertex_list_input_file = "vertices-compass.csv.gz"
verbose = true

[mapping]
type = "edge"
geometry_input_file = "edges-geometries-enumerated.txt.gz"
tolerance.distance = 15.0
tolerance.unit = "meters"
queries_without_destinations = false
matching_type = ["point", "vertex_id", "edge_id"]

[traversal]
type = "distance"
distance_unit = "miles"

[access]
type = "turn_delay"
edge_heading_input_file = "edges-headings-enumerated.csv.gz"

[plugin]
[[plugin.input_plugins]]
type = "grid_search"

[[plugin.input_plugins]]
type = "load_balancer"

[plugin.input_plugins.weight_heuristic]
type = "haversine"
[[plugin.output_plugins]]
type = "summary"

[[plugin.output_plugins]]
type = "traversal"
route = "geo_json"
geometry_input_file = "edges-geometries-enumerated.txt.gz"

[access.turn_delay_model]
type = "tabular_discrete"
time_unit = "seconds"

[cost.weights]
distance = 1

[access.turn_delay_model.table]
no_turn = 0.0
slight_right = 0.5
right = 1.0
sharp_right = 1.5
slight_left = 1.0
left = 2.5
sharp_left = 3.5
u_turn = 9.5

[cost.vehicle_rates.distance]
type = "factor"
factor = 0.655
