name: Publish - crates.io

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Crates.io
    environment: crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --all --manifest-path=rust/Cargo.toml

      - name: Publish routee-compass-core
        run: cargo publish -p routee-compass-core --token "${{ secrets.CRATES_IO_TOKEN }} --manifest-path=rust/Cargo.toml"

      - name: Publish routee-compass-powertrain
        run: cargo publish -p routee-compass-powertrain --token "${{ secrets.CRATES_IO_TOKEN }} --manifest-path=rust/Cargo.toml""

      - name: Publish routee-compass
        run: cargo publish -p routee-compass --token "${{ secrets.CRATES_IO_TOKEN }} --manifest-path=rust/Cargo.toml"

      - name: Publish routee-compass-macros
        run: cargo publish -p routee-compass-macros --token "${{ secrets.CRATES_IO_TOKEN }} --manifest-path=rust/Cargo.toml""

      - name: Publish routee-compass-py
        run: cargo publish -p routee-compass-py --token "${{ secrets.CRATES_IO_TOKEN }} --manifest-path=rust/Cargo.toml"
